# Generated by Django 4.1.7 on 2023-03-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0005_meet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
